### PR TITLE
improve speed minimal

### PR DESCRIPTION
**Pull request by openpaul**
I just tested the code a little with the python profiler (https://docs.python.org/2/library/profile.html) and found that there where some unnecessary updates of the GUI. Some I could remove, some I could not.

Each redrawing of the plasmid and the editor costs a lot of time. So the code can be improed and the updates should only occur if needed.

On function that calls updates stupidly is the OnSize function in the editor (dnaEditorCairo_GUI.py line 632). This function is also the one responsible for the flickering on resize. Also it is the function that makes the buffer for the canvas. So if you have any idea regarding this function, it would certainly speed up the code very much.

### CODE REVIEW

**Comment by mengqvist** [comment]
I've had a look at that function. It gets called about 9-11 times for each resize or when opening a new file. This is certainly not right and I'm sure it contributes to the slowdown as you say. The funny thing is that you can remove the whole function and the flickering on resize disappears. Several features of the program does not work any more of course, but it does indicate that a solution is possible. I will look at it some more.

**Comment by mengqvist** [comment]
I should also mention that the events seem to originate from the DNAedit class in main.py. This is not so surprising since it holds the panels for the DNA editor and the plasmid view. I feel like the solution is to tweak that part somehow. I think the OnSize function as such is probably ok. We just need to make sure it gets called less.

**Comment by mengqvist** [comment]
I just had a look at the plasmid_GUI script and it gets by just fine without a re-defined OnSize function. I really think that the solution here will be to get rid of it in the DNA editor as well. Parts of the functionality will likely need to be re-implemented elsewhere.

**Comment by mengqvist** [comment]
I've made and committed some changes that take care of the flickering. Basically moved some of the OnSize functionality to the update_ownUI function. The flickering seems to come when the program "inserts" the scrollbars. So I tweaked the width parameter of the parent panel and now it does not flicker any more. We still get an insane number of UI updates for every event that in my mind should only update the UI once. But that is a different matter so solve.

**Comment by openpaul** [comment]
Nice, looks like this bug is fixed. Thank you.
I think (and hope) we will sooner or later find the reason for the unnecessary updates.

**Pull request merged**
