### PR TITLE
Experimental editor

### PR DESCRIPTION
**Pull request by openpaul**
I suggest using pango and cairo as a basis to create and design a useful dna editing editor.

This editor has the capability to show sense and anti-sense strains of the dna while also being able to display more features and informations. It is therefore more practical then the previous editor.

editor

On the other side the speed is not as good as with a pure text window.

As this was written in a first attempt to understand pango, it may be, that some huge design mistakes where made. But i do not think so.

This commit is based on this commit: https://github.com/mengqvist/DNApy/pull/30 and should be merged afterwards. It also removs the feature edit panel and suggest adding and removing features should be done via a context menu (yet to be done).

I am open to suggestions or other ideas, how to better display DNA and meta informations at the same time.

### CODE REVIEW

**Comment by mengqvist** [comment]
This new editor looks really great! It's very much like what I had in mind for a more graphical editor. I think we are both inspired by SnapGene when it comes to the graphics. 

Two things:
The speed of this new editor is really quite slow. Could we speed it up by only drawing the bases which are currently viewed? If we could use the scrollbar to get the position of the molecule currently in view, then we could only draw those bases and features. What do you think?

I also noticed a whole bunch of bugs concerning selection/copying/pasting of DNA bases and how one interacts with the graphics in general. This is true both for the plasmid view and the new dna editor. I strongly feel that we could consolidate and iron out those bugs before we continue with adding more features to the editor. These is the very basic functions that should work. I don't want the number of bugs to get out of control and at the same time I want DNApy to be usable even though it is being heavily modified. I'll put in some work towards squashing some bugs in the near future.

**Comment by openpaul** [comment]
first of all, thank you.

yes the bugs: As I had two branches working it was very difficult to find a nice way to make selection work, as I changed the internals quite a bit. Now I came to terms to use (1,-1,-1) as a reference, meaning position 1, no selection and not selected over the origin. I will iron out those bugs in the next few days, so the basic functionality is given again.

About the speed:
It is quite slow while typing. I think only showing what we need might work. But as I was and am currently still not very happy with how the canvas is sized in the scroll window it was a minor aspect for me until now. I would be happy if you had time to look at the code and maybe adjust it, as I think you have more knowledge about frames and windows in wxpython, then me. Try resizing the window and you will see how badly the canvas reshapes.

But all in all, I think it is the right way to go. I am currently thinking about how to make the whole development more stable and was thinking about maybe writing some standards down (as the selection value) to make the design more consistent?

**Comment by mengqvist** [comment]
I also think that we are certainly moving in the right direction with the new DNA editing window! It is just way more slick and can display more information. Getting the editor and the plasmid view working right and being stable is the main nut to crack. Adding on bells and whistles in separate editing windows after that should be fairly strait forward. 

As was noted (by you?) in the source another important thing to fix is how to parse the corrupted files from VectorNTI and co. If we want people to use DNApy they need to be able to open their old files. Most people have no idea that .gb != .gb. I know I didn't. I used to explicitly save files in .gb so they would be portable. I hate vendor lockdown. Yet, for me it was a mystery for a long time why my ApE files would not render on my colleagues computers...

I can take a look at the resizing problems. For my understanding though, when you talk about the resizing problem, do you mean that the DNA bases are "jumping around" or the fact that when the left border of the window is moved only the plasmid view window gets smaller, not the dna editing view? Or both?

**Comment by openpaul** [comment]
Yes,  I agree with you completely. The parser issue should be resolved to make exchange of documents possible. Also we should produce clean and nice genbank files and not add any fancy extras. As of now it is what the parser does, I think.

There are two resizing issues:
First of all, resizing the window always incerases or decreases only the plasmid view. This is due to the splitters and I did not know hopw to resolv this.

The oder thing is that resizing the editor by using the middle sizer (the one seperating the plasmidview and the editor) will result in some short flickering (see (mini) gif)

bloggif_55c1f8fe86241

**Pull request merged**
